experiment:
  name: res64_k_32_with_probe_fourier_modes
  model: nonGAN                  # GAN, nonGAN
  generator: FNO              # FNO, UNet
  inputHeads: 3
  outputHeads: 5

path:
  trainingData: /Users/kapoor/Articles/article1_FNO_UNet/data/elasto_plastic/64
  testingData: /Users/kapoor/Articles/article1_FNO_UNet/data/elasto_plastic/testing
  saveModel: /Users/kapoor/Articles/githubGAN/mmGAN/saved_models
  inference: /Users/kapoor/Articles/githubGAN/mmGAN/inferences

dataProcessing:
  scaler: MinMax              # MinMax or Gaussian

model: 
  UNet:
    version: standard         # standard or standard_from_output or standard_from_enc or modified 
    kernel: 9
    encChannels: 
                - 16
                - 32
                - 64
                - 128
    decChannels:
                - 128
                - 64
                - 32
                - 16
    interfaceChannels: 256

  FNO:
    version: standard         # standard or standard_from_firstFL or standard_from_thirdFL or dropout or amplitude
    modes1: 32
    modes2: 32
    width: 32
    dropout: 0.8
    probeFourierModes: True

  GAN: 
    discriminatorVersion: UNet     # UNet-enc or original or modified
    LAMBDA: 100

# TODO: define metric and loss function
training:
  continueTraining: False
  epochs: 200
  trainValTestSplit:
                  - 800
                  - 100
                  - 100
  batchSize: 16
  learningRate: 0.001
  gamma: 0.5
  weightDecay: 0.0001
  stepSize: 100
  lossFunction: L1      # L1 or L2 or normalDist
  metric: L1            # L1 or L2

inference:
  # set include and exclude to null to get inference for all test cases
  # if include is not null, only the specified tests will be used
  # if exclude is not null, all but the specified tests will be used
  nTest: 10 
  include: 
        - '64'
        - '256'
        - 'aspect_ratio_64'
        - 'aspect_ratio_128'
        - 'aspect_ratio_256'
        - 'aspect_ratio_512'
        - 'aspect_ratio_1024'
        - 'aspect_ratio_2048'
        # - '512'
  exclude:
        - 2048_1280grains

postprocessing:
  # set include and exclude to null to get postprocess for all test cases
  # if include is not null, only the specified tests will be used
  # if exclude is not null, all but the specified tests will be used
  include:
        - '64'
        - '256'
        - 'aspect_ratio_64'
        - 'aspect_ratio_128'
        - 'aspect_ratio_256'
        - 'aspect_ratio_512'
        - 'aspect_ratio_1024'
        - 'aspect_ratio_2048'
        # - '512'
  exclude:
        - 2048_1280grains
  functions:
        - aggregatedError
        - plotFields
        - plotErrorFields
        # - plotMeanErrorFields
        # - plotValueHistograms
        # - plotErrorHistograms
        - gradientFieldsTRUE
        - gradientFieldsPRED
        # - mechEquilibriumCondition
        # - periodicityCondition
        - FourierAnalysis 
  plotFieldCMap: viridis
  plotErrorFieldCMap: seismic
  plotGradientFieldCMap: Reds
  overwriteLogger: False