experiment:
  name: test
  model: nonGAN            # GAN, nonGAN
  generator: UNet       # FNO, UNet
  inputHeads: 3
  outputHeads: 5

path:
  data: /Users/kapoor/Articles/article1_FNO_UNet/data/elasto_plastic/64
  saveModel: /Users/kapoor/Articles/githubGAN/mmGAN/saved_models

dataProcessing:
  scaler: MinMax    # MinMax or Gaussian

model: 
  UNet:
    version: standard
    kernel: 9
    encChannels: 
                - 16
                - 32
                - 64
                - 128
    decChannels:
                - 128
                - 64
                - 32
                - 16
    interfaceChannels: 256

  FNO:
    version: standard
    modes1: 20
    modes2: 20
    width: 32

  GAN: 
    discVersion: UNet-enc
    LAMBDA: 


training:
  continueTraining: False
  epochs: 2
  trainValTestSplit:
                  - 80
                  - 100
                  - 100
  batchSize: 2
  learningRate: 0.001
  gamma: 0.5
  weightDecay: 0.0001
  stepSize: 100

inference:
  # by default, all the test cases in the data folder will be used
  # if include is not None, only the specified tests will be used
  # if exclude is not None, all but the specified tests will be used
  include: None
  exclude: None